# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: The Robotic Capybara
subtitle:
description: A platform for discussing topics in the intersection of Robotics and Software Engineering. Under-explored topics and unique actionable information.
keywords:
author: Eduardo Rocha
author_website: https://rocha.one
language: en
timezone: America/Chicago

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://capybot.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cactus

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

###########################################################################
# Theme override
###########################################################################
theme_config:
  colorscheme: dark_custom

  # Maximal width of the page in rem units.
  page_width: 48

  # Link to a page that gives an overview of all your projects.
  # This can be an external link (e.g., to you GitHub profile) or to another
  # page within your website.
  projects_url: https://github.com/capyrobot

  # Configure the navigation menu.
  # A pair 'Key: url' will result in a link to 'url' with the name 'Key' in the
  # navigation menu. Optionally, you can add translations for the 'Key' in
  # languages/*.yml
  nav:
    home: /
    about: /about/
    articles: /archives/
    projects: https://github.com/capyrobot

  # Links to your social media accounts.
  # The keys should correspond to Fontawesome icon names
  # (see https://fontawesome.com/icons?d=gallery&s=brands);
  # only 'mail' is an exception.
  social_links:
    github: https://github.com/capyrobot
    linkedin: https://www.linkedin.com/in/eduardo-rocha-a26029107/
    mail: mailto:eduardo@rocha.com

  # Customize the overview with displaying a tagcloud on the index page.
  # Options: https://hexo.io/docs/helpers.html#tagcloud
  tags_overview: false

  # Customize the overview with the most recent blog posts on the index page.
  # Options:
  #   - show_all_posts: whether to show all available posts.
  #   - post_count: whether to show only the x most recent posts.
  #   - sort_updated: sort posts by last modification date instead of creation date.
  posts_overview:
    show_all_posts: false
    post_count: 5
    sort_updated: false

  # Customize the archive view.
  # Options:
  #   - sort_updated: sort posts by last modification date instead of creation date.
  # Note: this does not work together with pagination, since the pagination
  # plugin will sort pages by date of creation.
  archive:
    sort_updated: false

  # Customize the article view.
  # Options:
  #   - show_updated: show the last modification date.
  post:
    show_updated: false

  # Customize the copyright years
  # Note: if start_year/end_year not provided, will use current year.
  copyright:
    start_year: 2022
    end_year:

  # Customize the logo (i.e., the cactus) in the header.
  # Options:
  #   - enabled: whether to show (true) or hide (false) the logo.
  #   - width: width of the logo in pixel units
  #   - height: height of the logo in pixel units
  #   - url: where the logo can be found
  #   - gravatar: whether to use your Gravatar as the logo
  #   - grayout: whether to enable a hover effect on the logo
  logo:
    enabled: true
    width: 50
    height: 50
    url: /images/Capybot-compressed.jpg
    gravatar: false
    grayout: true